### ISSUE TITLE
Question about UWB anchor ground truth positions in MCD dataset

### ISSUE THREAD

**Issue by ser666** [mcdviral/mcdviral.github.io#11]
Hello,

I am currently working on a project involving UWB positioning systems, and I am using the MCD dataset. However, I couldn’t find the ground truth positions of the UWB anchors in different scenes. Could you please confirm whether this information is included in the dataset? If not, is there any way to obtain it?

Thank you for your help!

**Comment by snakehaihai** [comment]
Hi. we did put it somewhere. But we also forget the link.

The detailed position will be updated in the GT part and some other localization packages.

**Comment by brytsknguyen** [comment]
Hi @ser666 ,

Below is the coordinates of the UWB anchors in the ntu sequences. U may need to add a (100, -100, -20) offset to them to align with the ground truth.

I am still looking for the values related to the KTH and TUHH sequences.

```
ntu_world:
    anchor_0:
        T:
        - [ 1.0, 0.0, 0.0, -55.9598010 ]
        - [ 0.0, 1.0, 0.0,  206.505188 ]
        - [ 0.0, 0.0, 1.0,  30.9622170 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_1:
        T:
        - [ 1.0, 0.0, 0.0,  53.2652090 ]
        - [ 0.0, 1.0, 0.0,  124.708542 ]
        - [ 0.0, 0.0, 1.0,  27.8654940 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_2:
        T:
        - [ 1.0, 0.0, 0.0,  132.937271 ]
        - [ 0.0, 1.0, 0.0,  45.4240380 ]
        - [ 0.0, 0.0, 1.0,  26.6453040 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_3:
        T:
        - [ 1.0, 0.0, 0.0,  231.095978 ]
        - [ 0.0, 1.0, 0.0, -74.6742710 ]
        - [ 0.0, 0.0, 1.0,  19.8915920 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_4:
        T:
        - [ 1.0, 0.0, 0.0,  97.2890550 ]
        - [ 0.0, 1.0, 0.0, -106.648407 ]
        - [ 0.0, 0.0, 1.0,  15.0182290 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_5:
        T:
        - [ 1.0, 0.0, 0.0, -57.0730670 ]
        - [ 0.0, 1.0, 0.0, -118.516457 ]
        - [ 0.0, 0.0, 1.0,  15.7623250 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_6:
        T:
        - [ 1.0, 0.0, 0.0, -116.521507 ]
        - [ 0.0, 1.0, 0.0, -70.5435790 ]
        - [ 0.0, 0.0, 1.0,  18.0772610 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_7:
        T:
        - [ 1.0, 0.0, 0.0, -152.360474 ]
        - [ 0.0, 1.0, 0.0,  64.5029680 ]
        - [ 0.0, 0.0, 1.0,  29.6708410 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_8:
        T:
        - [ 1.0, 0.0, 0.0, -56.5982550 ]
        - [ 0.0, 1.0, 0.0,  42.7576100 ]
        - [ 0.0, 0.0, 1.0,  21.8050580 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_9:
        T:
        - [ 1.0, 0.0, 0.0, -12.7728810 ]
        - [ 0.0, 1.0, 0.0,  74.0770870 ]
        - [ 0.0, 0.0, 1.0,  22.7475150 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
kth_world:
    anchor_0:
        T:
        - [ 1.0, 0.0, 0.0,  96.1214830 ]
        - [ 0.0, 1.0, 0.0,  49.4342540 ]
        - [ 0.0, 0.0, 1.0,  41.6374930 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_1:
        T:
        - [ 1.0, 0.0, 0.0, -45.2739830 ]
        - [ 0.0, 1.0, 0.0,  74.6381230 ]
        - [ 0.0, 0.0, 1.0,  38.6001050 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_2:
        T:
        - [ 1.0, 0.0, 0.0, -72.8684230 ]
        - [ 0.0, 1.0, 0.0, -6.31082200 ]
        - [ 0.0, 0.0, 1.0,  33.8108750 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_3:
        T:
        - [ 1.0, 0.0, 0.0,  17.6498660 ]
        - [ 0.0, 1.0, 0.0, -98.8498000 ]
        - [ 0.0, 0.0, 1.0,  30.2081780 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_4:
        T:
        - [ 1.0, 0.0, 0.0,  119.888779 ]
        - [ 0.0, 1.0, 0.0, -115.542542 ]
        - [ 0.0, 0.0, 1.0,  31.4469700 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_5:
        T:
        - [ 1.0, 0.0, 0.0,  214.377899 ]
        - [ 0.0, 1.0, 0.0, -60.8545990 ]
        - [ 0.0, 0.0, 1.0,  28.6625040 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_6:
        T:
        - [ 1.0, 0.0, 0.0,  118.112625 ]
        - [ 0.0, 1.0, 0.0,  16.5811120 ]
        - [ 0.0, 0.0, 1.0,  40.3582120 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_7:
        T:
        - [ 1.0, 0.0, 0.0,  90.7574840 ]
        - [ 0.0, 1.0, 0.0, -64.8034520 ]
        - [ 0.0, 0.0, 1.0,  32.2915150 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_8:
        T:
        - [ 1.0, 0.0, 0.0,  54.656124 ]
        - [ 0.0, 1.0, 0.0,  2.6239700 ]
        - [ 0.0, 0.0, 1.0,  34.826149 ]
        - [ 0.0, 0.0, 0.0,  1.0000000 ]
    anchor_9:
        T:
        - [ 1.0, 0.0, 0.0,  117.930359 ]
        - [ 0.0, 1.0, 0.0, -48.5400430 ]
        - [ 0.0, 0.0, 1.0,  34.0373800 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
tuhh_world:
    anchor_0:
        T:
        - [ 1.0, 0.0, 0.0,  6.00975400 ]
        - [ 0.0, 1.0, 0.0, -83.4949190 ]
        - [ 0.0, 0.0, 1.0,  92.2019730 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_1:
        T:
        - [ 1.0, 0.0, 0.0,  5.63282900 ]
        - [ 0.0, 1.0, 0.0,  44.5906560 ]
        - [ 0.0, 0.0, 1.0,  97.3119430 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_2:
        T:
        - [ 1.0, 0.0, 0.0,  61.5259780 ]
        - [ 0.0, 1.0, 0.0, -41.8280410 ]
        - [ 0.0, 0.0, 1.0,  96.2018740 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_3:
        T:
        - [ 1.0, 0.0, 0.0,  48.6745150 ]
        - [ 0.0, 1.0, 0.0, -117.579071 ]
        - [ 0.0, 0.0, 1.0,  95.7107240 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_4:
        T:
        - [ 1.0, 0.0, 0.0,  40.5483890 ]
        - [ 0.0, 1.0, 0.0,  75.3853000 ]
        - [ 0.0, 0.0, 1.0,  99.4134140 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_5:
        T:
        - [ 1.0, 0.0, 0.0, -6.80773400 ]
        - [ 0.0, 1.0, 0.0, -46.7692570 ]
        - [ 0.0, 0.0, 1.0,  92.2392960 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_6:
        T:
        - [ 1.0, 0.0, 0.0,  25.2880290 ]
        - [ 0.0, 1.0, 0.0, -232.545654 ]
        - [ 0.0, 0.0, 1.0,  87.7002640 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_7:
        T:
        - [ 1.0, 0.0, 0.0,  7.18283300 ]
        - [ 0.0, 1.0, 0.0, -271.747559 ]
        - [ 0.0, 0.0, 1.0,  81.3762280 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_8:
        T:
        - [ 1.0, 0.0, 0.0, -34.1195620 ]
        - [ 0.0, 1.0, 0.0, -351.485382 ]
        - [ 0.0, 0.0, 1.0,  85.7215650 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]
    anchor_9:
        T:
        - [ 1.0, 0.0, 0.0,  35.7247470 ]
        - [ 0.0, 1.0, 0.0, -335.608887 ]
        - [ 0.0, 0.0, 1.0,  83.7757640 ]
        - [ 0.0, 0.0, 0.0,  1.00000000 ]

```
